name: CI

run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
      - develop
      - 'release/*'
      - 'feature/*'
  pull_request:
    branches:
      - master
      - develop
      - 'release/*'
      - 'feature/*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install httpx
        pip install pytest-asyncio
        pip install fastapi
        pip install pydantic

    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff --output-format=github .
      continue-on-error: true

    - name: Run Pytest tests
      run: python -m pytest


