name: CI

run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
      - develop
      - 'release/*'
      - 'feature/*'
  pull_request:
    branches:
      - master
      - develop
      - 'release/*'


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install httpx
        pip install pytest-asyncio
        pip install fastapi
        pip install pydantic

    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff --output-format=github .
      continue-on-error: true

    - name: Run Pytest tests
      run: python -m pytest --junitxml=reports/xunit-results.xml

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: . # Adjust this if your project is in a subdirectory
        args: >
          -Dsonar.projectKey=kenlong2206_trade-assistant-fastapi
          -Dsonar.organization=kenlong2206
          -Dsonar.host.url=https://sonarcloud.io # or your SonarQube server URL
          -Dsonar.python.xunit.reportPath=reports/xunit-reports/xunit-result.xml
          -Dsonar.python.version=3

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: reports/xunit-reports/xunit-result.xml
