name: CI

on:
  push:
    branches:
      - master
      - develop
      - 'release/*'
      - 'feature/*'
  pull_request:
    branches:
      - master
      - develop
      - 'release/*'
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install httpx
        pip install pytest-asyncio

    - name: Run tests
      run: pytest
